language: go
go:
  - 1.8

services:
  - docker

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

env:
  global:
    - BRANCH=$(echo $TRAVIS_BRANCH | sed -e "s,/,_,g;")
    - DOCKER_IMAGE_TAG=$BRANCH-${TRAVIS_COMMIT::8}
    - DOCKER_REGISTRY=quay.io
    - secure: "melMg+kKRoNImATX8OZQPC3HG2IlfDE7MfqjBr5+Ns48T8SNkOVJ/7yvWgWichjKQOur7y6cMaWtzA5j6RKJlbbGV4X4NKnQtz4bjAUBAVBQbJeddlVU2sDrEgtbBorNzP/2L/UDGgvGW1xSAHYt26EBJn4dbVsGSgf/sO0EmV3eIGso2QDJeKD2JL+nK0BFKhWV7zU9NnlYdGYyQ0QRFhDPdEhtY1EwET8uBgnmOYtMmZfvRA4nUfMSIVfpIjh8wUGQnjNaunXvXjoiMP1t5tdHADqo8r8HorpkEZbqFAVYpyezCdmouJjcjAcZZlX0NCFwaUsDGhLkbR5viGmt0g9iJ4vEASBXiZOju84Vq2Clie+IeHwaZx+E/ZbY6xbfEM0cwEWfiTApbUZCF5pnNcK2NlXO4gNmcyoHT1UWFa5xB0BdhoJe978GaiXLgWRyUkIkWtFF6d1yOZfWRSg7ZlPjj3pyF2NYv/Smw6ecY76dJh6p6BtD7+VkaEDFIhyFXGoLV/aJ60Xjvm00ZqR5Rjd/uJUW+vwH38aSXfpu405+KrydfGj1IsXTL7DE4rO6gt0Zoq7Z92YDMp3y3lAOSPayP7u35rTXNjlLpoeMi31Qj8i9WByfL9iQVa+AfQQIfTW72PP/NSaaRvn6zKC2PFoRmWtDYuhEl10DPSPAE8E="
    - secure: "VM31HpaG6W5R8TJQfB7n4Av1GPRz5y3gxGnOdm10kf1JMrXnkz8Uuv3DXrM6QPebFqIA0eExNIS/8GwDRxNVTcY+QZ572ZEJGwS1EqhFunjy1ljwTbl3Yw5oCfkmLuNY7nc9g0fAklChjA+QkkOXk6hAI0g0l3Pb5Ps8xNmbTQVq61Lgch5Xqx0RX9irv6C38+QHLRaDbWzyku+I7tywzMU/J3Dy3uT70xLsUUuGwVxrqJy/UKqSKidw3L3cQkr2vAJl8IigDbkaI/Wd27/VjrFOjpHRLlc3fp4HG4lob0uptDv4UCxBXX64fbzdsE+KNPkmBpuJUSsR9TJ9IGax4dJ8i+aJr2OrgJlk3WmU+UgD1ygXLdDdQMWGhA88xdSh3VhpeTvhwauosSxOU3G2nrcaIUdEePlbI+rouN+gN95Eq96PkNm7pyHBFGd6oEOexyqMy/AK2LnydMCYe50Jvez3FLuB3iJTIl8Ufh5mWrshnrnzo99ncUoA0JoTdtGLrvgY4PqStpU1vBnGUQFAe7qn5qCSQ81IFJB45lUTE4zX0mnUZ01ulFGzO0fX6pw5EExUxtYhCYUE8Wze8HlUMFBMstAdLz+Ap9WBizmdaTzkkwvT/vvUo+7qx6ukD4aCseMuwP69VKa06C+LtwfKaIB/asQQ4DbFq05vd0tWAAg="

before_install:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD" $DOCKER_REGISTRY

install:
  - glide install

script:
  - make test

deploy:
  - provider: script
    skip_cleanup: true
    script: make ci-build
    on:
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: make docker-update-latest
    on:
      branch: master
