version: "3"
services:
  app:
    build: .
    #image: bgpat/tweet-via-searchbar:latest
    depends_on:
      - redis
    env_file: .env
    environment:
      REDIS_URL: redis:6379
    links:
      - redis
    ports:
      - "8080:8080"
  redis:
    image: redis:alpine
